@ProductsManagement_HostAddress = http://localhost:5085

GET {{ProductsManagement_HostAddress}}/api/products/
Accept: application/json

### Get Product By Id
GET {{ProductsManagement_HostAddress}}/api/products/1
Accept: application/json

### Update a Product

PUT {{ProductsManagement_HostAddress}}/api/products/1
Accept: application/json
Content-Type: application/json
{
  "id": 2,
  "name": "Smartphone",
  "description": "Smartphone Product2 2026",
  "price": 120.99
}

### Add a Product

POST {{ProductsManagement_HostAddress}}/api/products/
Accept: application/json
Content-Type: application/json
{
  "id": 2,
  "name": "Smartphone",
  "description": "Smartphone Product2 2026",
  "price": 120.99
}

### Delete a Product

DELETE {{ProductsManagement_HostAddress}}/api/products/3 
Accept: application/json

